[build]
  command = "npm run build"
  publish = ".next"


[functions]
    directory = "netlify/functions"
    included_files = ["node_modules/sharp/**/*", ".blurDataURLsCache/**/*"]
    node_bundler = "esbuild"

[[plugins]]
  package = "/plugins/img-placeholder-cache"
