query CategoryArchiveTeamMembers($category: [String]!, $page: Int!, $per_page: Int!) {
  TeammemberItems(
    page: $page
    per_page: $per_page
    filter_query_v2: { team_category: { in_array: $category } }
    resolve_links: "url"
  ) {
    items {
      content {
        first_name
        last_name
        job_title
        vip
        team_category
        image {
          filename
          alt
        }
        _uid
        team_category
      }
      full_slug
    }
    total
  }
}
