query IndividualTeamMember($slug: ID!) {
  TeammemberItem(id: $slug, resolve_links: "url") {
    content {
      _editable
      _uid
      component
      first_name
      last_name
      job_title
      image {
        filename
        alt
      }
      intro_content
      content
      sidebar_content
      team_category
      vip
      linked_in {
        cachedUrl
        url
        linktype
        id
      }
      email {
        cachedUrl
        fieldtype
        linktype
        url
      }
    }
    full_slug
    uuid
    name
  }
}
