query AllBlogArticles($page: Int!, $per_page: Int!) {
  BlogarticleItems(page: $page, per_page: $per_page, resolve_links: "url") {
    items {
      content {
        _editable
        _uid
        category
        component
        content
        date
        featured_image {
          alt
          filename
        }
        title
      }
      slug
      created_at
      published_at
    }
    total
  }
}
